export const PRODUCT_CATEGORIES = [
  "Alimentos",
  "Bebidas",
  "Panaderia y Reposteria",
  "Frutas y Verduras",
  "Hogar",
  "Hogar y Decoracion",
  "Belleza y Cuidado Personal",
  "Ropa y Accesorios",
  "Calzado",
  "Tecnologia y Accesorios",
  "Electrohogar",
  "Mascotas",
  "Salud y Bienestar",
  "Bebes y Ninos",
  "Deportes",
  "Jugueteria",
  "Arte y Manualidades",
  "Papeleria y Oficina",
  "Ferreteria",
  "Automotriz",
  "Jardineria",
  "Limpieza",
  "Farmacia",
  "Servicios Profesionales",
  "Servicios para el Hogar",
  "Educacion y Cursos",
  "Eventos y Catering",
  "Turismo y Experiencias",
  "Libros y Revistas",
  "Otros",
] as const;
